#!/usr/bin/env bash
# Regenerate .claude/project-structure.md — directory tree snapshot.
# Called by /wrap-up (Step 3b) and /start can reference the output.
#
# Produces a depth-limited tree excluding node_modules, .git, __pycache__, etc.
# Truncated at 200 lines to stay within context budget.

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
STRUCTURE_FILE="$PROJECT_DIR/.claude/project-structure.md"

{
  echo "# Project Structure"
  echo ""
  echo "_Auto-generated by wrap-up. Last updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)_"
  echo ""
  echo '```'

  # Use find to build a tree (cross-platform, no dependency on 'tree' command)
  find "$PROJECT_DIR" -maxdepth 4 -type d \
    -not -path "*/node_modules*" \
    -not -path "*/.git/*" \
    -not -path "*/.git" \
    -not -path "*/__pycache__*" \
    -not -path "*/.ruff_cache*" \
    -not -path "*/.mypy_cache*" \
    -not -path "*/.pytest_cache*" \
    -not -path "*/dist/*" \
    -not -path "*/.next*" \
    -not -path "*/.antigravity*" \
    -not -path "*/.claude/logs*" \
    -not -path "*/coverage*" \
    2>/dev/null \
    | sed "s|^$PROJECT_DIR/||" \
    | sort \
    | head -200

  echo '```'
  echo ""

  # Count files by type
  echo "## File Counts"
  echo ""
  echo "| Extension | Count |"
  echo "|-----------|-------|"

  find "$PROJECT_DIR" -type f \
    -not -path "*/node_modules*" \
    -not -path "*/.git/*" \
    -not -path "*/__pycache__*" \
    -not -path "*/.antigravity*" \
    -not -path "*/dist/*" \
    2>/dev/null \
    | sed 's/.*\.//' \
    | sort \
    | uniq -c \
    | sort -rn \
    | head -15 \
    | while read -r count ext; do
        echo "| .$ext | $count |"
      done

  echo ""

} > "$STRUCTURE_FILE"
