#!/usr/bin/env bash
# PostToolUse hook: regenerate .claude/project-stack.md when structural files change.
#
# Structural files: package.json, requirements.txt, Dockerfile*, docker-compose*.yml,
# tsconfig*.json, Cargo.toml, go.mod, pyproject.toml, *.config.js, *.config.ts,
# Makefile, Gemfile, build.gradle, pom.xml
#
# Input: $CLAUDE_TOOL_INPUT (JSON with file_path)
# This hook is async — does not block the user.

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
STACK_FILE="$PROJECT_DIR/.claude/project-stack.md"

# Extract the file path that was just written/edited
FILE_PATH="$(echo "${CLAUDE_TOOL_INPUT:-}" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('file_path', ''))
except:
    print('')
" 2>/dev/null || echo "")"

[ -n "$FILE_PATH" ] || exit 0

# Check if the changed file is structural
BASENAME="$(basename "$FILE_PATH")"
case "$BASENAME" in
  package.json|requirements.txt|pyproject.toml|Cargo.toml|go.mod|go.sum|\
  Gemfile|Gemfile.lock|build.gradle|pom.xml|Makefile|justfile|\
  tsconfig.json|tsconfig.*.json|*.config.js|*.config.ts|*.config.mjs|\
  Dockerfile|Dockerfile.*|docker-compose*.yml|docker-compose*.yaml|\
  .env.example|setup.py|setup.cfg)
    ;;  # structural — proceed
  *)
    exit 0  # not structural — skip
    ;;
esac

# --- Regenerate project-stack.md ---

# Collect dependency manifests
collect_deps() {
  local label="$1" file="$2"
  if [ -f "$PROJECT_DIR/$file" ]; then
    echo "### $label"
    echo '```'
    # For package.json, extract only dependencies + devDependencies
    if [[ "$file" == *package.json ]]; then
      python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    d = json.load(f)
for section in ('dependencies', 'devDependencies', 'peerDependencies'):
    deps = d.get(section, {})
    if deps:
        print(f'{section}:')
        for k, v in sorted(deps.items()):
            print(f'  {k}: {v}')
" "$PROJECT_DIR/$file" 2>/dev/null || head -50 "$PROJECT_DIR/$file"
    elif [[ "$file" == *requirements.txt ]]; then
      grep -v '^\s*#' "$PROJECT_DIR/$file" | grep -v '^\s*$' | head -80
    else
      head -60 "$PROJECT_DIR/$file"
    fi
    echo '```'
    echo ""
  fi
}

{
  echo "# Project Stack"
  echo ""
  echo "_Auto-generated by hook. Last updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)_"
  echo ""

  # Detect runtimes
  echo "## Runtimes Detected"
  echo ""
  # Node.js — detect package manager from lockfile
  if find "$PROJECT_DIR" -maxdepth 3 -name "package.json" -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/.claude/*" -not -path "*/ai-operations-registry/*" -not -path "*/Daily Notes/*" 2>/dev/null | head -1 | grep -q .; then
    if [ -f "$PROJECT_DIR/pnpm-lock.yaml" ] || find "$PROJECT_DIR" -maxdepth 2 -name "pnpm-lock.yaml" 2>/dev/null | head -1 | grep -q .; then
      echo "- **Node.js** (pnpm)"
    elif [ -f "$PROJECT_DIR/yarn.lock" ] || find "$PROJECT_DIR" -maxdepth 2 -name "yarn.lock" 2>/dev/null | head -1 | grep -q .; then
      echo "- **Node.js** (yarn)"
    elif [ -f "$PROJECT_DIR/bun.lockb" ]; then
      echo "- **Node.js** (bun)"
    else
      echo "- **Node.js** (npm)"
    fi
  fi
  # Python
  if find "$PROJECT_DIR" -maxdepth 4 -name "requirements.txt" -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/.claude/*" -not -path "*/ai-operations-registry/*" -not -path "*/Daily Notes/*" 2>/dev/null | head -1 | grep -q .; then
    echo "- **Python** (pip)"
  elif [ -f "$PROJECT_DIR/pyproject.toml" ]; then
    echo "- **Python** (pyproject)"
  fi
  [ -f "$PROJECT_DIR/Cargo.toml" ] && echo "- **Rust** (cargo)"
  [ -f "$PROJECT_DIR/go.mod" ] && echo "- **Go** (modules)"
  [ -f "$PROJECT_DIR/Gemfile" ] && echo "- **Ruby** (bundler)"
  echo ""

  # Docker
  echo "## Docker"
  echo ""
  for f in $(find "$PROJECT_DIR" -maxdepth 3 \( -name "docker-compose*.yml" -o -name "docker-compose*.yaml" -o -name "Dockerfile" -o -name "Dockerfile.*" \) -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/.claude/*" 2>/dev/null | sort); do
    rel="${f#$PROJECT_DIR/}"
    echo "- \`$rel\`"
  done
  echo ""

  # Dependency manifests
  echo "## Dependencies"
  echo ""

  # Find all package.json (up to depth 3, skip node_modules)
  for pj in $(find "$PROJECT_DIR" -maxdepth 3 -name "package.json" -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/.claude/*" -not -path "*/ai-operations-registry/*" -not -path "*/Daily Notes/*" 2>/dev/null | sort); do
    rel="${pj#$PROJECT_DIR/}"
    collect_deps "Node: $rel" "$rel"
  done

  # Python
  for req in $(find "$PROJECT_DIR" -maxdepth 4 -name "requirements.txt" -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/.claude/*" -not -path "*/ai-operations-registry/*" -not -path "*/Daily Notes/*" 2>/dev/null | sort); do
    rel="${req#$PROJECT_DIR/}"
    collect_deps "Python: $rel" "$rel"
  done

  # Other manifests
  for mf in pyproject.toml Cargo.toml go.mod; do
    [ -f "$PROJECT_DIR/$mf" ] && collect_deps "$mf" "$mf"
  done

  # Config files
  echo "## Configuration Files"
  echo ""
  for cfg in $(find "$PROJECT_DIR" -maxdepth 3 \( -name "tsconfig*.json" -o -name "*.config.js" -o -name "*.config.ts" -o -name "*.config.mjs" -o -name ".env.example" \) -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/.claude/*" -not -path "*/ai-operations-registry/*" -not -path "*/Daily Notes/*" 2>/dev/null | sort); do
    rel="${cfg#$PROJECT_DIR/}"
    echo "- \`$rel\`"
  done
  echo ""

} > "$STACK_FILE"
