"""Tier 4b — Semantic memory of historical market episodes (Qdrant).

A *market episode* captures a meaningful regime or event detected from OHLCV
data — trend reversals, volatility spikes, volume surges, consolidation
breakouts. Each episode is embedded and stored in Qdrant so the Analyst can
retrieve historically similar situations before making a decision.

Example narrative:
    "BTC/USDT 2025-11-15 to 2025-11-22 1h — High volatility regime (CV=4.2%).
     Sharp uptrend: +12.3% over 168 candles. RSI peaked at 78.
     Volume surge 2.4x baseline in first 24h. SMA5 crossed above SMA13 at start."

Design notes:
- Each episode covers a *window* of candles (not a single point). The window
  size depends on the detection algorithm (typically 20-100 candles).
- Doc ID is deterministic: ``{symbol}:{timeframe}:{window_end_ts_epoch}`` so
  re-running the generator is idempotent (upsert, not duplicate).
- The collection is separate from trade_narratives and trdex_context.
- Detection runs offline (via generate_episodes.py script), not in the hot
  path of agent cycles.
"""

from __future__ import annotations

import hashlib
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone

from qdrant_client import AsyncQdrantClient
from qdrant_client.models import (
    Distance,
    FieldCondition,
    Filter,
    HnswConfigDiff,
    MatchValue,
    PointStruct,
    ScoredPoint,
    VectorParams,
)

from trdex.backtest.indicators import (
    classify_volatility,
    rsi_from_list,
    sma_from_list,
    volume_ratio,
)
from trdex.config import get_settings
from trdex.context.embeddings import EMBEDDING_DIM, JinaEmbedder

logger = logging.getLogger(__name__)

COLLECTION_NAME = "trdex_market_episodes"


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class MarketEpisode:
    """One detected market episode, ready for embedding + storage."""

    symbol: str
    timeframe: str
    episode_type: str  # trend_reversal | volatility_spike | volume_surge | consolidation_breakout | regime_change
    start_time: datetime
    end_time: datetime
    text: str = ""  # narrative — generated by build_episode_text if empty

    # Metrics at episode time
    price_change_pct: float = 0.0
    volatility_regime: str = "unknown"  # low | medium | high
    volatility_cv: float | None = None
    rsi_start: float | None = None
    rsi_end: float | None = None
    volume_ratio_peak: float | None = None
    sma_short: float | None = None
    sma_long: float | None = None
    candle_count: int = 0

    # Deterministic doc_id for idempotency
    doc_id: str = field(default="")

    def __post_init__(self) -> None:
        if not self.doc_id:
            self.doc_id = self._compute_doc_id()

    def _compute_doc_id(self) -> str:
        """Deterministic ID: hash of symbol:timeframe:end_timestamp."""
        end_epoch = int(self.end_time.timestamp())
        raw = f"{self.symbol}:{self.timeframe}:{end_epoch}"
        return hashlib.sha256(raw.encode()).hexdigest()[:32]


@dataclass
class MarketEpisodeHit:
    """A semantic search result from the episode collection."""

    doc_id: str
    score: float
    text: str
    symbol: str
    timeframe: str
    episode_type: str
    price_change_pct: float
    volatility_regime: str
    payload: dict


# ---------------------------------------------------------------------------
# Episode detection from OHLCV data
# ---------------------------------------------------------------------------


def detect_episodes(
    symbol: str,
    timeframe: str,
    timestamps: list[datetime],
    closes: list[float],
    volumes: list[float],
    window: int = 50,
    stride: int = 25,
) -> list[MarketEpisode]:
    """Detect market episodes from OHLCV close/volume data using a sliding window.

    Scans the data with a sliding window and classifies each window into
    episode types based on indicator thresholds. Only windows with a
    significant event are emitted.

    Args:
        symbol: Trading pair.
        timeframe: Candle timeframe string.
        timestamps: Ordered list of candle open times.
        closes: Ordered close prices (same length as timestamps).
        volumes: Ordered volumes (same length as timestamps).
        window: Number of candles per episode window.
        stride: Step between windows (controls overlap).

    Returns:
        List of detected MarketEpisode objects.
    """
    n = len(closes)
    if n < window:
        return []

    episodes: list[MarketEpisode] = []

    for start_idx in range(0, n - window + 1, stride):
        end_idx = start_idx + window
        w_closes = closes[start_idx:end_idx]
        w_volumes = volumes[start_idx:end_idx]
        w_start = timestamps[start_idx]
        w_end = timestamps[end_idx - 1]

        # Compute indicators for this window
        regime, cv = classify_volatility(w_closes, window=min(20, window))
        pct_change = (w_closes[-1] - w_closes[0]) / w_closes[0] * 100 if w_closes[0] != 0 else 0.0
        rsi_start = rsi_from_list(w_closes[:20], period=14) if len(w_closes) >= 20 else None
        rsi_end = rsi_from_list(w_closes, period=14)
        vol_ratio = volume_ratio(w_volumes, window=min(20, window))
        sma_s = sma_from_list(w_closes, 5)
        sma_l = sma_from_list(w_closes, 13)

        # Classify episode type based on signals
        episode_type = _classify_window(
            pct_change=pct_change,
            regime=regime,
            cv=cv,
            vol_ratio=vol_ratio,
            rsi_end=rsi_end,
            sma_short=sma_s,
            sma_long=sma_l,
        )

        if episode_type is None:
            continue  # Not significant enough

        episode = MarketEpisode(
            symbol=symbol,
            timeframe=timeframe,
            episode_type=episode_type,
            start_time=w_start,
            end_time=w_end,
            price_change_pct=round(pct_change, 3),
            volatility_regime=regime,
            volatility_cv=round(cv, 5) if cv else None,
            rsi_start=round(rsi_start, 1) if rsi_start else None,
            rsi_end=round(rsi_end, 1) if rsi_end else None,
            volume_ratio_peak=round(vol_ratio, 2) if vol_ratio else None,
            sma_short=round(sma_s, 2) if sma_s else None,
            sma_long=round(sma_l, 2) if sma_l else None,
            candle_count=window,
        )
        episode.text = build_episode_text(episode)
        episodes.append(episode)

    return episodes


def _classify_window(
    *,
    pct_change: float,
    regime: str,
    cv: float | None,
    vol_ratio: float | None,
    rsi_end: float | None,
    sma_short: float | None,
    sma_long: float | None,
) -> str | None:
    """Classify a window into an episode type, or None if unremarkable.

    Priority order (first match wins):
    1. Volume surge: vol_ratio > 2.0x
    2. Volatility spike: high regime with CV > 4%
    3. Trend reversal: abs(pct_change) > 5% with RSI extreme
    4. Consolidation breakout: low regime followed by pct_change > 3%
    5. Regime change: medium/high transition (CV boundary)

    Returns None if the window doesn't meet any threshold.
    """
    # 1. Volume surge
    if vol_ratio is not None and vol_ratio > 2.0:
        return "volume_surge"

    # 2. Volatility spike
    if regime == "high" and cv is not None and cv > 0.04:
        return "volatility_spike"

    # 3. Trend reversal (strong directional move + RSI extreme)
    if abs(pct_change) > 5.0:
        if rsi_end is not None and (rsi_end > 70 or rsi_end < 30):
            return "trend_reversal"

    # 4. Consolidation breakout (was low vol, now moved)
    if regime == "low" and abs(pct_change) > 3.0:
        return "consolidation_breakout"

    # 5. Regime change (high vol with moderate move)
    if regime == "high" and abs(pct_change) > 2.0:
        return "regime_change"

    return None


def build_episode_text(episode: MarketEpisode) -> str:
    """Render a deterministic, embedding-friendly narrative from a MarketEpisode."""
    start_str = episode.start_time.strftime("%Y-%m-%d %H:%M")
    end_str = episode.end_time.strftime("%Y-%m-%d %H:%M")

    parts: list[str] = [
        f"{episode.symbol} {start_str} to {end_str} {episode.timeframe}",
        f"— {episode.episode_type.replace('_', ' ').title()}.",
    ]

    # Volatility
    if episode.volatility_cv is not None:
        parts.append(f"{episode.volatility_regime.title()} volatility (CV={episode.volatility_cv*100:.1f}%).")

    # Price move
    direction = "uptrend" if episode.price_change_pct > 0 else "downtrend"
    parts.append(f"{'Sharp ' if abs(episode.price_change_pct) > 5 else ''}{direction}: {episode.price_change_pct:+.1f}% over {episode.candle_count} candles.")

    # RSI
    if episode.rsi_end is not None:
        rsi_label = ""
        if episode.rsi_end > 70:
            rsi_label = " (overbought)"
        elif episode.rsi_end < 30:
            rsi_label = " (oversold)"
        parts.append(f"RSI at end: {episode.rsi_end:.0f}{rsi_label}.")

    # Volume
    if episode.volume_ratio_peak is not None:
        parts.append(f"Volume {episode.volume_ratio_peak:.1f}x baseline.")

    # SMA cross
    if episode.sma_short is not None and episode.sma_long is not None:
        if episode.sma_short > episode.sma_long:
            parts.append("SMA5 above SMA13 (bullish).")
        else:
            parts.append("SMA5 below SMA13 (bearish).")

    return " ".join(parts)


# ---------------------------------------------------------------------------
# Qdrant store
# ---------------------------------------------------------------------------


class MarketEpisodeStore:
    """Async Qdrant wrapper for the ``trdex_market_episodes`` collection."""

    def __init__(self, client: AsyncQdrantClient | None = None) -> None:
        self._client = client

    async def _get_client(self) -> AsyncQdrantClient:
        if self._client is None:
            settings = get_settings()
            self._client = AsyncQdrantClient(
                url=settings.qdrant_url, check_compatibility=False
            )
        return self._client

    async def ensure_collection(self) -> None:
        """Create the collection on first use (idempotent)."""
        client = await self._get_client()
        existing = [c.name for c in (await client.get_collections()).collections]
        if COLLECTION_NAME not in existing:
            await client.create_collection(
                collection_name=COLLECTION_NAME,
                vectors_config=VectorParams(
                    size=EMBEDDING_DIM,
                    distance=Distance.COSINE,
                    hnsw_config=HnswConfigDiff(m=16, ef_construct=100),
                ),
            )
            logger.info("[market_episodes] created collection %s", COLLECTION_NAME)

    async def upsert(
        self,
        episodes: list[MarketEpisode],
        vectors: list[list[float]],
    ) -> None:
        """Insert/update a batch of episodes with their precomputed vectors."""
        if not episodes:
            return
        if len(episodes) != len(vectors):
            raise ValueError("episodes and vectors must have the same length")

        client = await self._get_client()
        points = [
            PointStruct(
                id=ep.doc_id,
                vector=v,
                payload={
                    "text": ep.text,
                    "symbol": ep.symbol,
                    "timeframe": ep.timeframe,
                    "episode_type": ep.episode_type,
                    "start_time": ep.start_time.isoformat(),
                    "end_time": ep.end_time.isoformat(),
                    "price_change_pct": ep.price_change_pct,
                    "volatility_regime": ep.volatility_regime,
                    "volatility_cv": ep.volatility_cv,
                    "rsi_start": ep.rsi_start,
                    "rsi_end": ep.rsi_end,
                    "volume_ratio_peak": ep.volume_ratio_peak,
                    "sma_short": ep.sma_short,
                    "sma_long": ep.sma_long,
                    "candle_count": ep.candle_count,
                },
            )
            for ep, v in zip(episodes, vectors, strict=True)
        ]
        await client.upsert(collection_name=COLLECTION_NAME, points=points)

    async def search(
        self,
        query_vector: list[float],
        *,
        symbol: str | None = None,
        episode_type: str | None = None,
        limit: int = 5,
    ) -> list[ScoredPoint]:
        """Top-k semantic search with optional filters."""
        client = await self._get_client()
        must: list[FieldCondition] = []
        if symbol:
            must.append(FieldCondition(key="symbol", match=MatchValue(value=symbol)))
        if episode_type:
            must.append(FieldCondition(key="episode_type", match=MatchValue(value=episode_type)))
        query_filter = Filter(must=must) if must else None
        response = await client.query_points(
            collection_name=COLLECTION_NAME,
            query=query_vector,
            query_filter=query_filter,
            limit=limit,
            with_payload=True,
        )
        return response.points

    async def count(self, symbol: str | None = None) -> int:
        """Count episodes in the collection, optionally filtered by symbol."""
        client = await self._get_client()
        info = await client.get_collection(COLLECTION_NAME)
        if symbol is None:
            return info.points_count or 0
        # Filtered count via scroll with limit=0 is not supported;
        # use a large limit count approach
        response = await client.count(
            collection_name=COLLECTION_NAME,
            count_filter=Filter(must=[
                FieldCondition(key="symbol", match=MatchValue(value=symbol))
            ]) if symbol else None,
            exact=True,
        )
        return response.count

    async def close(self) -> None:
        if self._client:
            await self._client.close()
            self._client = None


# ---------------------------------------------------------------------------
# Service
# ---------------------------------------------------------------------------


class MarketEpisodeService:
    """High-level API for writing and querying market episodes.

    Handles embedding + storage roundtrip. Callers don't need to know about
    vectors or Qdrant directly.

    Usage::

        service = MarketEpisodeService()
        await service.setup()
        await service.record_batch(episodes)
        hits = await service.search("BTC high volatility breakout", symbol="BTC/USDT")
    """

    def __init__(
        self,
        embedder: JinaEmbedder | None = None,
        store: MarketEpisodeStore | None = None,
    ) -> None:
        self._embedder = embedder or JinaEmbedder()
        self._store = store or MarketEpisodeStore()

    async def setup(self) -> None:
        await self._store.ensure_collection()

    async def record_batch(self, episodes: list[MarketEpisode]) -> int:
        """Embed and store a batch of episodes. Returns count stored."""
        if not episodes:
            return 0
        # Ensure text is populated
        for ep in episodes:
            if not ep.text:
                ep.text = build_episode_text(ep)

        async with self._embedder as embedder:
            vectors = await embedder.embed([ep.text for ep in episodes])
        await self._store.upsert(episodes, vectors)
        logger.info("[market_episodes] recorded %d episodes", len(episodes))
        return len(episodes)

    async def search(
        self,
        query: str,
        *,
        symbol: str | None = None,
        episode_type: str | None = None,
        limit: int = 5,
    ) -> list[MarketEpisodeHit]:
        """Find episodes semantically similar to ``query``."""
        async with self._embedder as embedder:
            qvec = await embedder.embed_query(query)
        hits = await self._store.search(
            qvec, symbol=symbol, episode_type=episode_type, limit=limit
        )
        return [self._hit_from_point(h) for h in hits]

    async def search_similar_context(
        self,
        symbol: str,
        closes: list[float],
        volumes: list[float],
        *,
        limit: int = 3,
    ) -> list[MarketEpisodeHit]:
        """Find episodes similar to the current market state.

        Builds a description of the current conditions from recent closes/volumes,
        then does a semantic search to find historical episodes that looked similar.
        """
        # Build a query description from current indicators
        regime, cv = classify_volatility(closes)
        sma_s = sma_from_list(closes, 5)
        sma_l = sma_from_list(closes, 13)
        rsi_val = rsi_from_list(closes, 14)
        vol_r = volume_ratio(volumes)
        pct = (closes[-1] - closes[-20]) / closes[-20] * 100 if len(closes) >= 20 and closes[-20] != 0 else 0.0

        parts = [f"{symbol} current conditions:"]
        parts.append(f"{regime} volatility")
        if cv:
            parts.append(f"(CV={cv*100:.1f}%)")
        parts.append(f"price change {pct:+.1f}% over 20 candles")
        if rsi_val:
            parts.append(f"RSI={rsi_val:.0f}")
        if vol_r:
            parts.append(f"volume {vol_r:.1f}x baseline")
        if sma_s and sma_l:
            cross = "bullish" if sma_s > sma_l else "bearish"
            parts.append(f"SMA cross {cross}")

        query = " ".join(parts)
        return await self.search(query, symbol=symbol, limit=limit)

    async def close(self) -> None:
        await self._store.close()

    @staticmethod
    def _hit_from_point(point: ScoredPoint) -> MarketEpisodeHit:
        payload = point.payload or {}
        return MarketEpisodeHit(
            doc_id=str(point.id),
            score=float(point.score),
            text=payload.get("text", ""),
            symbol=payload.get("symbol", ""),
            timeframe=payload.get("timeframe", ""),
            episode_type=payload.get("episode_type", ""),
            price_change_pct=payload.get("price_change_pct", 0.0),
            volatility_regime=payload.get("volatility_regime", "unknown"),
            payload=payload,
        )
